### ISSUE TITLE
allow defining backend services in toml config

### ISSUE THREAD

**Issue by xmonader** [xmonader/tcprouter#6]
something like

```toml

[server.services]
    [server.services.ruby]
        sni = "www.ruby-lang.org"
        addr = "151.101.1.178:443"
```
